services:
  elasticsearch:
    image: elasticsearch:8.15.0
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - elk
  kibana:
    image: kibana:8.15.0
    ports:
      - "5601:5601"
- 
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    networks:
      - elk
  codesphere.cache:
    image: redis:latest
    networks:
      - elk
    restart: always
    ports:
      - "6379:6379"
    

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch-data: